Repository emi-12d/100math, pull requests merged in 2025-10, with the labels that each got.

#10 Issue/5
  main.py
Labels: wontfix

#9 Issue/7
  Makefile
  generator.py
Labels: bug, enhancement

#14 feat: 🎸 警告文の修正とMakefileに便利なコマンドを一つ追加
  Makefile
  main.py
Labels: enhancement, wontfix
